#!/usr/bin/env python
# vim:set ts=4 sw=4 

# make a horizontal bar chart

#from pylab import *
from matplotlib.pyplot import barh, title, grid , savefig, yticks 
import matplotlib.pyplot
import numpy as np
#val =         [1, 2, 3, 4, 5]
#pos = arange(len(val))+.5    # the bar centers on the y axis
#yticks(pos, ('Tom', 'Dick', 'Harry', 'Slim', 'Jim'))


in_file = open("in-file", "r")
in_title = in_file.readline()
in_val = []
in_lable = []

while True:
	in_line = in_file.readline()
	if not in_line:
		break
	in_line = in_line[:-1]
	line_val, line_lable = in_line.split(",")
	in_val.append(int(line_val))
	in_lable.append(line_lable)	
in_file.close()

pos = np.arange(len(val))+.5  
yticks(pos, tuple(in_lable))
print 'yt args: ', (pos, tuple(in_lable))
print 'val: ', val
print 'pos: ', pos
print 'lable: ', in_lable


barh(pos,in_val, align='center')
xlabel('Performance')
title(in_title)
grid(True)
savefig("t.png")


